//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcAngularJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.EmployeeTables = new HashSet<EmployeeTable>();
        }
    
        public int ID { get; set; }
        public string DepartmentName { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual ICollection<EmployeeTable> EmployeeTables { get; set; }
    }
}
